### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by samtstern** [yogeshhk/MidcurveNN#5]
Hello! We'd love to include this repository on https://devlibrary.withgoogle.com but we need the repository to have an explicit LICENSE file (either MIT or Apache 2.0) before we can host the content.

Would you mind adding one? After you do that this link will automatically work (within 24h of the update):
https://devlibrary.withgoogle.com/products/ml/repos/yogeshhk-MidcurveNN

**Comment by yogeshhk** [comment]
Added MIT License
